# server.py
from mcp.server.fastmcp import FastMCP
from typing import Dict
from pull_request import list_open_pr, get_diff, add_comment

# Create an MCP server
mcp = FastMCP("Demo")


# Add an addition tool
@mcp.tool()
def add(a: int, b: int) -> int:
    """Add two numbers"""
    return a + b


# Add a dynamic greeting resource
@mcp.resource("greeting://{name}")
def get_greeting(name: str) -> str:
    """Get a personalized greeting"""
    return f"Hello, {name}!"

@mcp.tool("get-pull-requests", description="Get pull request for the repo")
def get_pull_request(repo_name: str) -> Dict:
    response = list_open_pr(repo_name)
    return response

@mcp.tool("get-diff", description="Get diff for the pull request, requires the diff_url before that to fetch diff_url run the get-pull-request ")
def get_diff_details(diff_url: str) -> bytes:
    response = get_diff(diff_url)
    return response

@mcp.tool("add-comment", description="Create an comment for the pull request, before running this, first we need to call the pull request, and the get the diff and the response generated by the diff need to be used as comment")
def get_diff_details(repo_name: str, pull_number: int, response: str) -> Dict:
    response = add_comment(repo_name,pull_number,response)
    return response

if __name__ == "__main__":
    mcp.run()